<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.73.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Widgets\" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
	<Exec Command="xcopy &quot;$(OutDir)*.dll&quot; &quot;$(SolutionDir)DashboardApp\Widgets\&quot; /Y" />
  </Target>

</Project>
