<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Contracts\Contracts.csproj" />
	</ItemGroup>

	<!-- ⭐ Automatyczne kopiowanie DLL do Plugins -->
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(TargetPath)"
			  DestinationFolder="$(SolutionDir)DashboardApp\bin\Debug\net8.0-windows\Plugins" />
	</Target>

</Project>
