<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.ComponentModel.Composition" Version="10.0.5" />
	</ItemGroup>

	<!-- Automatyczne kopiowanie Contracts.dll do Plugins -->
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SolutionDir)DashboardApp\bin\Debug\net8.0-windows\Plugins" />
	</Target>

</Project>
